### ISSUE TITLE
Firefox 40 no longer supports the widget module

### ISSUE THREAD

**Issue by jscher2000** [badams/translator-firefox-addon#8]
Extensions dies. Thread on Mozilla Support: https://support.mozilla.org/questions/1078319

**Comment by badams** [comment]
Hey @jscher2000 thanks for letting me know about this. I might have been a bit too trusting of the automated compatibility tests the AMO performs prior to a release.

Could you provide a pull request for the changes you made?

**Comment by jscher2000** [comment]
Hi Byron, all I did in my workaround was comment out the code that referenced the widget module. 

I see that the new way to do a toolbar button is to use ui.ActionButton (https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/ui) but I'm not an add-on developer and am not familiar with the fine points.

I probably should learn how to do that, and what a pull request is, but please don't count on me for this.

**Comment by badams** [comment]
No worries @jscher2000 I'll take a look and try get a fix out for this soon.

**Comment by badams** [comment]
Hi @jscher2000 I've released a new version of translator which addresses this issue its still waiting to be reviewed on AMO, but you can download it here https://addons.mozilla.org/en-US/firefox/addon/translator/versions/?page=1#version-2.0.4

I would appreciate if you could update your answer on support.mozilla.org

thanks!

**Comment by jscher2000** [comment]
SuMo updated, thanks for the quick fix.
